### ISSUE TITLE
NullReferenceException Error

### ISSUE THREAD

**Issue by asoft2013** [6ameDev/Advanced-Pooling-System#1]
Hi first of all thanks for great object pool system!!!

I' ve got an error when i set Pool Expand to false. For example I set Default Pool amount = 3. Unity creates 3 prefab and then throw NullReferenceException? because there is no checks on second overload of this method
public GameObject InstantiateAPS (string itemType, Vector3 itemPosition, Quaternion itemRotation)

NullReferenceException: Object reference not set to an instance of an object
PoolingSystem.InstantiateAPS (System.String itemType, Vector3 itemPosition, Quaternion itemRotation) (at Assets/Advanced Pooling System/PoolingSystem.cs:111)

**Comment by 6ameDev** [comment]
Hello @asoft2013 
Thank you for reporting this issue, it has been fixed now. A warning message shows up in the log now, instead of the NullReferenceException error.

**Comment by asoft2013** [comment]
Hi ! good news!  thanks for reply

Среда, 28 января 2015, 3:30 -08:00 от Sumit Das notifications@github.com:
